In [1]:
import torch

In [2]:
t1=torch.tensor(4.)

In [3]:
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
#Vector
t2=torch.tensor([1,2,3,4])
t2

tensor([1, 2, 3, 4])

In [6]:
 t3=torch.tensor([[1,2,3],[4,5,6]])
 t3

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
t4=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
t4

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [9]:
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [10]:
t2.dtype

torch.float32

In [11]:
t1.shape

torch.Size([])

In [12]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [13]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [17]:
# Its not possible to create tensor with improper shape
t5=torch.tensor([[1,2,3],[4,5,6],[7,8]])
t5

ValueError: expected sequence of length 3 at dim 1 (got 2)

In [18]:
x=torch.tensor(4.)
w=torch.tensor(3.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(4.), tensor(3., requires_grad=True), tensor(5., requires_grad=True))

In [19]:
y=w*x+b

In [20]:
y

tensor(17., grad_fn=<AddBackward0>)

In [22]:
import numpy as np

In [23]:
lst=[3,4,5,6]
arr=np.array(lst)
arr

array([3, 4, 5, 6])

In [24]:
arr.dtype

dtype('int64')

In [25]:
#Convert numpy to pytorch tensors
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [27]:
#Indexing
tensors[:2]

tensor([3, 4])

In [28]:
tensors[2]

tensor(5)

In [29]:
tensors[1:4]

tensor([4, 5, 6])

In [30]:
tensors[3]=100

In [31]:
tensors

tensor([  3,   4,   5, 100])

In [32]:
arr

array([  3,   4,   5, 100])

In [33]:
# So tensors made from numpy function uses same value


In [35]:
tensor_arr=torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100])

In [36]:
tensor_arr[3]=120
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120])
[  3   4   5 100]


In [39]:
##Zeroes and ones
torch.zeros(2,3,dtype=torch.float64,requires_grad=True)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64, requires_grad=True)

In [40]:
torch.ones(2,3,dtype=torch.float64,requires_grad=True)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64, requires_grad=True)

In [41]:
#Arithmetic operations
a=torch.tensor([1,2,3,4])
b=torch.tensor([5,6,7,8])
print(a+b)

tensor([ 6,  8, 10, 12])


In [42]:
np.arange(0,15).reshape(5,3) # Gives array of 5 rows and 3columns

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [43]:
a=torch.tensor(np.arange(0,15).reshape(5,3))

In [44]:
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [45]:
a[:,1]

tensor([ 1,  4,  7, 10, 13])

In [46]:
a[1:]

tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [47]:
a[1:2]

tensor([[3, 4, 5]])

In [48]:
a[1:2,1]

tensor([4])

In [49]:
#Arithmetic operations
a=torch.tensor([1,2,3,4])
b=torch.tensor([5,6,7,8])

In [50]:
torch.add(a,b)

tensor([ 6,  8, 10, 12])

In [51]:
c=torch.zeros(3)

In [54]:
torch.add(a,b,out=c)  # here output is stored in c

tensor([ 6.,  8., 10., 12.])

In [55]:
c

tensor([ 6.,  8., 10., 12.])

In [56]:
torch.add(a,b).sum()

tensor(36)

In [57]:
a.mul(b) #Multiplication

tensor([ 5, 12, 21, 32])

In [58]:
x=torch.tensor([[1,4,2],[1,5,5]])
y=torch.tensor([[1,3],[4,6],[5,2]])

In [59]:
torch.matmul(x,y)

tensor([[27, 31],
        [46, 43]])

In [60]:
torch.mm(x,y)

tensor([[27, 31],
        [46, 43]])

In [61]:
x@y  # Matrix multiplication

tensor([[27, 31],
        [46, 43]])