In [1]:
#BackPropogation using Pytorch
import torch

In [2]:
x=torch.tensor(4.0,requires_grad=True)

In [3]:
y=x**2

In [4]:
y

tensor(16., grad_fn=<PowBackward0>)

In [5]:
### BackPropogation y=2*x
y.backward()   ## derivative of y=x**2

In [7]:
print(x.grad)   #computes value after putting x=2

tensor(8.)


In [9]:
lst=[[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]
torch_input=torch.tensor(lst,requires_grad=True)

In [10]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [19]:
### y=x**3+x**2
##  y=3x**2+2x --->
y=torch_input**3+torch_input**2

In [12]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [13]:
z=y.sum()

In [14]:
z

tensor(1040., grad_fn=<SumBackward0>)

In [16]:
z.backward()

In [17]:
z


tensor(1040., grad_fn=<SumBackward0>)

In [18]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])